chrome.driver.path=${USER_HOME}/.cache/selenium/chromedriver/mac-arm64/151.0.7922.76/chromedriver
base.url=https://automationexercise.com/
browser=chrome
browser.width=1920
browser.height=1080
page.load.timeout=30
script.timeout=30
implicit.wait=1
explicit.wait=8
headless=false
incognito=false