base.url=https://automationexercise.com/
api.base.url=https://automationexercise.com/api
browser=chrome
browser.width=1920
browser.height=1080
page.load.timeout=30
script.timeout=30
implicit.wait=1
explicit.wait=8
headless=false
incognito=false